from emoji import emojize
num=int(input('Informe um número para ver seu fatorial:'))
multiplicador=1
cont=num
print('{}! = '.format(num) .replace('0', emojize(':zero:', use_aliases=True))
      .replace('1',  emojize(':one:', use_aliases=True))
      .replace('2',  emojize(':two:', use_aliases=True))
      .replace('3', emojize(':three:', use_aliases=True))
      .replace('4', emojize(':four:', use_aliases=True))
      .replace('5', emojize(':five:', use_aliases=True))
      .replace('6', emojize(':six:', use_aliases=True))
      .replace('7', emojize(':seven:', use_aliases=True))
      .replace('8', emojize(':eight:', use_aliases=True))
      .replace('9', emojize(':nine:', use_aliases=True)), end='')
while cont > 0:
    multiplicador=multiplicador*cont
    print('{}'.format(cont) .replace('0', emojize(':zero:', use_aliases=True))
      .replace('1',  emojize(':one:', use_aliases=True))
      .replace('2',  emojize(':two:', use_aliases=True))
      .replace('3', emojize(':three:', use_aliases=True))
      .replace('4', emojize(':four:', use_aliases=True))
      .replace('5', emojize(':five:', use_aliases=True))
      .replace('6', emojize(':six:', use_aliases=True))
      .replace('7', emojize(':seven:', use_aliases=True))
      .replace('8', emojize(':eight:', use_aliases=True))
      .replace('9', emojize(':nine:', use_aliases=True)), end='')
    print(' x ' .replace('0', emojize(':zero:', use_aliases=True))
      .replace('1',  emojize(':one:', use_aliases=True))
      .replace('2',  emojize(':two:', use_aliases=True))
      .replace('3', emojize(':three:', use_aliases=True))
      .replace('4', emojize(':four:', use_aliases=True))
      .replace('5', emojize(':five:', use_aliases=True))
      .replace('6', emojize(':six:', use_aliases=True))
      .replace('7', emojize(':seven:', use_aliases=True))
      .replace('8', emojize(':eight:', use_aliases=True))
      .replace('9', emojize(':nine:', use_aliases=True)).replace('x', emojize(':heavy_multiplication_x:', use_aliases=True)) if cont > 1 else ' = ' .replace('0', emojize(':zero:', use_aliases=True))
      .replace('1',  emojize(':one:', use_aliases=True))
      .replace('2',  emojize(':two:', use_aliases=True))
      .replace('3', emojize(':three:', use_aliases=True))
      .replace('4', emojize(':four:', use_aliases=True))
      .replace('5', emojize(':five:', use_aliases=True))
      .replace('6', emojize(':six:', use_aliases=True))
      .replace('7', emojize(':seven:', use_aliases=True))
      .replace('8', emojize(':eight:', use_aliases=True))
      .replace('9', emojize(':nine:', use_aliases=True)), end='')
    cont-=1
print('{}'.format(multiplicador) .replace('0', emojize(':zero:', use_aliases=True))
      .replace('1',  emojize(':one:', use_aliases=True))
      .replace('2',  emojize(':two:', use_aliases=True))
      .replace('3', emojize(':three:', use_aliases=True))
      .replace('4', emojize(':four:', use_aliases=True))
      .replace('5', emojize(':five:', use_aliases=True))
      .replace('6', emojize(':six:', use_aliases=True))
      .replace('7', emojize(':seven:', use_aliases=True))
      .replace('8', emojize(':eight:', use_aliases=True))
      .replace('9', emojize(':nine:', use_aliases=True)))
